#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Let me run the Build once 🛠️"
pnpm run build
echo "✅✅✅ Testing and 🔎 Searching for mistakes in your code."
npx lint-staged
echo "✅✅✅ Great Work🎊 ✨ Accepting your Commit This Time ✅✅❤️"
